# Project information
site_name: Developer Resources | Keebox List ™
site_url: https://andriksantos.github.io/keebox/
site_author: Andrik Santos ™
site_description: >-
    Programming resources are all over the internet, but they're hard to track down. That's why this repository was born. Whose main objective is to collect as many programming resources as possible that exist on the internet, so that they are available to anyone at any time

#Menu
nav:
    - Resources of programming: index.md
    - node.js: nodejs.md
    - Electron: electron.md
    - Npm: npm.md
    - ios: ios.md
    - mac: mac.md
    - Swift: Swift.md
    - Contributing: contributing.md
    - Code of conduct: code-of-conduct.md

# Repository
repo_name: andriksantos/keebox
repo_url: https://github.com/andriksantos/keebox
edit_uri: ""

# Copyright
copyright: 'Copyright &copy; 2023 Andrik Santos ™'

#Configuration
theme: 
  name: material

  palette:
    # Light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/weather-sunny
        name: Switch to dark mode

    # Dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: indigo
      accent: indigo
      toggle:
        icon: material/weather-night
        name: Switch to light mode

  features:
    #- navigation.tabs
    - navigation.expand
    - navigation.top
    - search.suggest
    - search.highlight
    - search.share

favicon: assets/favicon.png
icon:
  logo: logo

# Static files
static_templates:
    - 404.html

# Don't include MkDocs' JavaScript
include_search_page: true
search_index_only: true

markdown_extensions:
    - admonition
    - abbr
    - attr_list
    - def_list
    - footnotes
    - meta
    - md_in_html

# Social Networks
extra:
  social:
    - icon: fontawesome/brands/github
      link: https://andriksantos.github.io/
      name: Visit my portfolio
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/andriksantos/
      name: Follow me on linkedin
    - icon: fontawesome/brands/instagram
      link: https://www.instagram.com/andriksantos1/
      name: andriksantos1 on instagram
    - icon: fontawesome/brands/whatsapp
      link: https://wa.me/50496679577
      name: write me on whatsapp

  alternate:
    - name: Español
      link: /es/ 
      lang: es
    - name: English
      link: /en/
      lang: en


# Google Analytics
google_analytics:
  - 'UA-169388687-1'
  - 'auto'

extra_javascript:
- javascripts/shortcuts.js

extra_css:
  - stylesheets/extra.css

